src/Entity/Articles.php
<?php

namespace App\Entity;

use App\Repository\ArticlesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ArticlesRepository::class)
 */
class Articles
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @Gedmo\Slug(fields={"titre"})
     * @ORM\Column(length=128,unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @var \DateTime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     *  @var \DateTime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $module;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $semestre;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\ManyToMany(targetEntity=Filieres::class, inversedBy="articles")
     */
    private $Filiers;

    /**
     * @ORM\OneToMany(targetEntity=Files::class, mappedBy="articles", cascade={"persist"},orphanRemoval=true)
     */
    private $files;



    public function __construct()
    {
        $this->Filiers = new ArrayCollection();
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }



    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    
    public function getModule(): ?string
    {
        return $this->module;
    }

    public function setModule(string $module): self
    {
        $this->module = $module;

        return $this;
    }

    public function getSemestre(): ?string
    {
        return $this->semestre;
    }

    public function setSemestre(string $semestre): self
    {
        $this->semestre = $semestre;

        return $this;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|Filieres[]
     */
    public function getFiliers(): Collection
    {
        return $this->Filiers;
    }

    public function addFilier(Filieres $filier): self
    {
        if (!$this->Filiers->contains($filier)) {
            $this->Filiers[] = $filier;
        }

        return $this;
    }

    public function removeFilier(Filieres $filier): self
    {
        $this->Filiers->removeElement($filier);

        return $this;
    }

    /**
     * @return Collection|Files[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(Files $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setArticles($this);
        }

        return $this;
    }

    public function removeFile(Files $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getArticles() === $this) {
                $file->setArticles(null);
            }
        }

        return $this;
    }


}

src/Form/ArticlesType.php
<?php

namespace App\Form;

use App\Entity\Articles;
use App\Entity\Filieres;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticlesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class)
            ->add('contenu', CKEditorType::class)
            ->add('module', TextType::class)
            ->add('semestre', TextType::class)
            ->add('Filiers', EntityType::class,[
                'required' => true,
                'class' => Filieres::class,
                'label' => false,
                'choice_label' => 'nom',
                'multiple' => true,
                'attr' =>[
                    'class' =>'select-fil'
                ]
            ])
            ->add('files', FileType::class,[
                  'label' => false,
                'required' => false,
                  'multiple' => true,
                    'mapped' =>false
            ])
        ;

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Articles::class,
        ]);
    }

}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\ArticleSearch;
use App\Entity\Users;
use App\Form\ArticleSearchType;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ArticleController extends AbstractController
{
    /**
     * @Route("/articles", name="articles.index")
     */
    public function index(Request $request,PaginatorInterface $pagination): Response
    {
        $search= new ArticleSearch();
        $form=$this->createForm(ArticleSearchType::class,$search);
        $form->handleRequest($request);
        if($form->isSubmitted()&& $form->isValid()) {
            $donnees = $this->getDoctrine()->getRepository(Articles::class)->findbySearch($search);
            $articles=$pagination->paginate($donnees,$request->query->getInt('page',1),12);
            return $this->render('article/index.html.twig', [
                'articles'   => $articles,
                'formSearch' => $form->createView()
                ]);

        }
        $donnees = $this->getDoctrine()->getRepository(Articles::class)->findBy([],
        ['created_at' => 'desc']);
        $articles=$pagination->paginate($donnees,$request->query->getInt('page',1),12);
        return $this->render('article/index.html.twig', [
            'current_menu' => 'visité',
            'articles'   => $articles,
            'formSearch' => $form->createView()
        ]);
    }
    /**
     * @Route("/articles/enseignant//{id}", name="enseignant")
     */
    public function ArticlesUser(Users $users,PaginatorInterface $pagination,Request $request): Response
    {

        $donnees=$users->getArticles();
        $articles=$pagination->paginate($donnees,$request->query->getInt('page',1),12);

        return $this->render('home/show.articles.user.html.twig',[
            'user' => $users,
            'articles' => $articles
        ]);
    }
    /**
     * @Route("/articles/{module}", name="module")
     */
    public function ArticlesModule(string $module,PaginatorInterface $pagination,Request $request): Response
    {
        $search= new ArticleSearch();
       $search->setModuleSearched($module);
        $donnees = $this->getDoctrine()->getRepository(Articles::class)->findbySearch($search);
        $articles=$pagination->paginate($donnees,$request->query->getInt('page',1),12);
        return $this->render('home/show.articles.user.html.twig',[
            'module' => $module,
            'articles' => $articles
        ]);
    }


}

src/Controller/ArticlesController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Files;
use App\Form\ArticlesType;
use App\Repository\ArticlesRepository;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_PROF")
 * @Route("/mesarticles")
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/", name="articles_index", methods={"GET"})
     */
    public function index(UsersRepository $usersRepository): Response
    {
             $id=($this->getUser())->getId();
        return $this->render('articles/index.html.twig', [
            'current_menu1' => 'visité',
            'user' => $usersRepository->find($id)
        ]);
    }

    /**
     * @Route("/new", name="articles_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Articles();
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $article->setUsers($this->getUser());
            $files=$form->get('files')->getData();

            foreach ($files as $file){
                $fiches=md5(uniqid()).'.'.$file->guessExtension();
                $file->move($this->getParameter('files_directory'),$fiches);
                $fil=new Files();
                $fil->setOriginalName($file->getClientOriginalName());
                $fil->setName($fiches);
                $article->addFile($fil);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            $this->addFlash('message','votre article a bien été publié');

            return $this->redirectToRoute('articles_index');
        }

        return $this->render('articles/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articles_show", methods={"GET"})
     */
    public function show(Articles $article): Response
    {
        $url=$this->generateUrl('articles_show',['id' =>$article->getId()]);
        return $this->render('articles/show.html.twig', [
            'article' => $article,
            'url'=>$url
        ]);
    }

    /**
     * @Route("/{id}/edit", name="articles_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Articles $article): Response
    {
        $form = $this->createForm(ArticlesType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setUsers($this->getUser());
            $files=$form->get('files')->getData();
            foreach ($files as $file){
                $fiches=md5(uniqid()).'.'.$file->guessExtension();
                $file->move($this->getParameter('files_directory'),$fiches);
                $fil=new Files();
                $fil->setOriginalName($file->getClientOriginalName());
                $fil->setName($fiches);
                $article->addFile($fil);
            }

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('message','votre article a bien été modifié');

            return $this->redirectToRoute('articles_index');
        }

        return $this->render('articles/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="articles_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Articles $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('articles_index');
    }
    /**
     * @Route("/delete/file/{id}", name="articles_delete_file", methods={"DELETE"})
     */
    public function deleteImage(Request $request,Files $file): Response
    {
        $data= json_decode($request->getContent(),true);
        if ($this->isCsrfTokenValid('delete'.$file->getId(), $data['_token'])) {
            $nom = $file->getName();
            unlink($this->getParameter('files_directory') . '/' . $nom);
            $em = $this->getDoctrine()->getManager();
            $em->remove($file);
            $em->flush();

            return new JsonResponse(['success' => 1]);
        }
        return new JsonResponse(['error'=>'token invalide'],404);
    }
}

templates/articles/_delete_form.html.twig
<form method="post" action="{{ path('articles_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn  btn-danger " style="color: snow">Delete</button>
</form>

templates/articles/_form.html.twig
<div class="container site">
    <div class="sidebar">
        <h5>Pour </h5>
        {{ form_start(form) }}
             <div class="form-group ">
                {{ form_row(form.Filiers) }}
            </div>
          <div class="form-group">
            {{ form_row(form.semestre) }}
            </div>

    </div>
    <main class="main">
     <article class="contenu">
          <header class="card-header card-header-avatar">

               <div class="card-title">
                <div class="form-group">
                {{ form_row(form.titre) }}
                  </div>
                <div class="form-group">
                {{ form_row(form.module) }}
                    </div>
               </div>
            </header>
             <div class="card-body">

            {{ form_row(form.contenu) }}
              </div>
      <footer class="coter d-grid gap-2 col-6 mx-auto float-lg-right">
           <button class="btn " style="color:snow;background-color: #2051a9;width: 200px">{{ button_label|default('Enregistrer') }}</button>
        </footer>
     </article>
    </main>
    <aside class="aside">
        <article class="profil">
            <header class="card-header card-header-avatar">
                <div class="card-title">ajouter un fichier </div>
            </header>
            <div class="card-body">
                <div class="form-group " >
                    {{ form_row(form.files) }}
                </div>

            </div>
        </article>
        <div id="selected-files"></div>
        {# si la route est articles_edit on affiche les docs#}
        {% if app.request.attributes.get('_route') == 'articles_edit' %}
        <div class="sidebar-title">les fichiers  </div>
        <div class="file-list">
            {% for file in article.files %}
                       <div class="file">

                   <div class="file-body">
                       <a href="{{ asset('/uploadsFile/' ~ file.name)}}" class="file-name" >{{ file.originalName }} </a>
                       <a href="{{ path('articles_delete_file',{id: file.id}) }}"
                          data-delete data-token="{{ csrf_token('delete' ~ file.id) }}" class="file-add" style="color: red"> <i class="las la-trash-alt"style="width: auto;height: auto"></i>supprimer</a>
                </div>
                     </div>
            {% endfor %}

        </div>
            {{ form_end(form) }}
        {% endif %}
    </aside>




</div>

templates/articles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Articles{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.fd.css') }}">
{% endblock %}
{% block body %}
    <div class="container">
        <div class=" d-grid gap-2 position-absolute " style="top:80px;left:260px;">
            <a href="{{ path('articles_index') }}" class="btn btn-secondary  d-inline-block p-8 mr-2" role="button" style="color: snow;" data-toggle="tooltip" data-placement="top" title="revenez à la liste"><i class="las la-arrow-circle-left " style="width: 30px"></i></a>
        </div>
        <div class="big-title">
            <h2>Editer Article </h2>
            <div class="hr-title"></div>
        </div>

    {{ include('articles/_form.html.twig', {'button_label': 'Modifier'}) }}



    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/files.js') }}"></script>
{% endblock %}

templates/articles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles index{% endblock %}

{% block body %}
<div class="container">
    <div class="big-title">
        <h2> Mes Articles </h2>
        <div class="hr-title"></div>
    </div>
    {% for message in app.flashes('message') %}
    <div class="alert alert-success">
             {{ message }}
    </div>
 {% endfor %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th >Titre</th>
                <th>Publiè le</th>
                <th>Module</th>
                <th>Semestre</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in user.articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td >{{ article.titre }}</td>
                <td>{{ article.updatedAt ? article.updatedAt|date('d/m/y a h\\hi'): '' }}</td>
                <td>{{ article.module }}</td>
                <td>{{ article.semestre }}</td>
                <td class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <a href="{{ path('articles_show', {'id': article.id}) }}" class="btn btn-info d-inline-block mr-2" role="button" style="color: snow">show</a>
                    <a href="{{ path('articles_edit', {'id': article.id}) }}" class="btn btn-success d-inline-block mr-2 pr-lg-3" style="color: snow">edit</a>
                    {{ include('articles/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    <div class="d-grid gap-2 col-10 mx-auto ">
        <a href="{{ path('articles_new') }}"  class="btn btn-primary float-lg-right  " style="color:snow;width: 200px;">Create new</a>
    </div>
</div>

{% endblock %}

templates/articles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Articles{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/app.css') }}">
{% endblock %}
{% block body %}
<div class="container">
    <div class=" d-grid gap-2 position-absolute " style="top:80px;left:260px;">
        <a href="{{ path('articles_index') }}" class="btn btn-secondary  d-inline-block p-8 mr-2" role="button" style="color: snow;" data-toggle="tooltip" data-placement="top" title="revenez à la liste"><i class="las la-arrow-circle-left " style="width: 30px"></i></a>
    </div>
    <div class="big-title">
        <h2>Creer Article </h2>
        <div class="hr-title"></div>
    </div>


    {{ include('articles/_form.html.twig') }}

</div>
{% endblock %}
{% block javascripts %}

{% endblock %}

templates/articles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.titre }}{% endblock %}

{% block body %}
        <div class="container">
            {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    <div class="page-heading title-lg">
        <div class="container">
            <div class="container">
                <div class="big-title"> </div>
                <div class="row">
                    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
                        <h3>
                            <a  href="#" style="text-decoration: none;">
                                {{ article.titre }}
                            </a>
                        </h3>
                        <ul class="page-meta">
                            <li>
                                <i class="las la-folder-open"></i>
                                {% for filiere in article.Filiers %}
                                    <a href="{{ path('Filiere',{id:filiere.id,slug:filiere.slug})}}" style="text-decoration: none" class="subject-label">
                                        {{ filiere.nom}}
                                    </a>

                                {% endfor %}
                            </li>
                            <li  data-toggle="tooltip" data-placement="top" title="l'enseignant">
                                <a href="{{ path('enseignant', {'id': article.users.id}) }}">
                                    <i class="las la-user"></i>
                                    {{ article.users.prenom }}  {{ article.users.nom }}
                                </a>
                            </li>
                            <li data-toggle="tooltip" data-placement="top" title="Publiè le">
                                <i class="las la-clock"></i>
                                {{ article.updatedAt ? article.updatedAt|date('d/m/y a h\\hi'): '' }}
                            </li>
                           <li  data-toggle="tooltip" data-placement="top" title="Nombre de fichiers">
                                   <i class="las la-file"></i>
                                   {{ article.files|length }}
                           </li>

                        </ul>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                        <div class="page-options d-grid gap-2 d-md-flex justify-content-md-start">
                            <a href="{{ path('articles_index') }}" class="btn btn-secondary  d-inline-block p-8 mr-2" role="button" style="color: snow;" data-toggle="tooltip" data-placement="top" title="revenez à la liste"><i class="las la-arrow-circle-left " style="width: 30px"></i></a>

                            <a href="{{ path('articles_edit', {'id': article.id}) }}"  class="btn btn-success d-inline-block pr-lg-3" style="color: snow">edit</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="lessons">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                    <div class="lessons-list">
                        {{ article.contenu|raw }}
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                    <div class="widget">
                    <h3>
                        <i class="las la-cloud-download-alt"></i>
                        Fichiers
                    </h3>
                     <div class="widget-body">
                         <ul class="files-list">
                             {% for file in article.files %}
                                      <li>
                                          <div class="file-item">
                                         <a href="{{ asset('/uploadsFile/' ~ file.name)}}" class="file-name" >
                                             <i class="las la-file-alt"></i> {{ file.originalName }} </a>
                                          </div>
                                      <div style="clear: both;">

                                      </div>
                                      </li>
                             {% endfor %}
                         </ul>
                     </div>
                    </div>

                    <div class="widget share-course">
                        <h3>
                            <i class="las la-share-alt-square"></i>
                            Partagez le cours
                        </h3>
                        <div class="course-link-input">
                        <input class="form-control" value="{{absolute_url(url)}}"  readonly>
                        </div>
                        <ul class="list-unstyled share-buttons">
                            <li>
                                <a  class="sharing-button facebook" href="https://facebook.com/sharer/sharer.php?u={{absolute_url(url)}}" title="facebook" target="_blank">
                                    <i class="lab la-facebook-square"></i>
                                </a>
                            </li>
                            <li>
                                <a  class="sharing-button email" href="mailto:?subject={{article.titre}}&body={{absolute_url(url)}}" title="email" target="_blank">
                                    <i class="las la-envelope"></i>
                                </a>
                            </li>
                            <li>
                                <a  class="sharing-button whatsapp" href="https://api.whatsapp.com/send?text={{absolute_url(url)}}" title="whatsapp" target="_blank">
                                    <i class="lab la-whatsapp"></i>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>

    </div>


{% endblock %}